### ISSUE TITLE
Ability to ignore failure to lift

### ISSUE THREAD

**Issue by jordan9001** [trailofbits/maat#104]
While ideally sleigh would be able to lift all instructions, there are many occasions where it can not.

When attempting to use MAAT to follow a debugger trace, it would be nice if there were a way to ignore failure to lift an instruction. I would prefer being able to set an option for an engine that will let the lifter just lift as far as it can, and only return an error if no instructions could be lifted at all.

Maybe a simpler alternative to the above would be just to limit the number of instructions to be lifted to not be more than the number of instructions passed to `run`?

That way it would be possible to do something like:
```py
eng, dbg = init()
while True:
    dbg.step()
    try:
        stop = eng.run(1)
        if stop != STOP.INST_COUNT:
            # handle stops ...
    except LifterError:
        # fix up registers if maat gets out of sync with dbg
        # possible loss of fidelity and symbolic info if we can't lift an instruction
        fixup_registers(dbg, eng)
```

**Comment by jordan9001** [comment]
Happy to help with this, if this is a feature you would want.
I understand if you'd prefer that the lifter was just updated to support any currently unlift-able instructions encountered, and not try to compensate for this on the MAAT side.

**Comment by Boyan-MILANOV** [comment]
As a general development strategy I'd strongly lean towards improving the lifter to support new instructions rather than implementing workarounds in scripts. Contributing once to the lifter benefits everyone, contrary to everyone re-implementing their own local fixes for unsupported instructions over and over again. 

This being said, running into unsupported instructions is inevitable and I believe you are right in saying that we should provide a convenient way to deal with it.

> being able to set an option for an engine that will let the lifter just lift as far as it can, and only return an error if no instructions could be lifted at all

It should be possible to ignore lifting failures in the disassembler and, when trying to actually execute an un-liftable instruction, stop execution with `STOP.UNSUPPORTED_INST`.  I prefer to signal the error using the `info.stop` attribute rather than straight up throwing an exception. Ideally we should also expose the API to get both the raw bytes and the disassembly of the unsupported instruction in `info`, so that people can easily check what instruction is causing issues.
As regards implementation it should be enough to add an `INVALID` operation to the IR and use it when lifting unsupported instructions.

> Maybe a simpler alternative to the above would be just to limit the number of instructions to be lifted to not be more than the number of instructions passed to `run`? 

I also like this idea. Not to solve this particular issue though, but to avoid spending time lifting many instructions in cases were we're just interested in executing a couple. It'll be easy to implement as well, since the lifter already takes a parameter telling it a maximum number instructions to lift.

I think I can implement all the above pretty quickly but still need to find some time to do it :) do you need the fix ASAP? 

**PS**: out of curiosity, what instructions are failing? I think Maat's spec files are a bit outdated compared to upstream Ghidra, maybe the instructions have been added in the meantime.

**Comment by jordan9001** [comment]
That all sounds good to me! No need for an ASAP fix.
The failing instructions I have run into recently have been `xsave` and friends. They pop up in my `ld.so` for symbol resolution path.

**Comment by jordan9001** [comment]
Related to this, failure to lift instructions currently always show up as a `STOP.FATAL`, instead of a `STOP.UNSUPPORTED_INST`. Should `get_asm_inst` throw `unsupported_instruction_exception` instead? Or would that cover too many other issues a lifter could throw?

If you want I can submit a small pull request with just the lift up to `max_inst`, and returning `STOP.UNSUPPORTED_INST` if `lift_block` throws an exception.

**Comment by Boyan-MILANOV** [comment]
Mmh such a workaround would work but I'm in favour in implementing the solution described in my previous comment: https://github.com/trailofbits/maat/issues/104#issuecomment-1141469882. As you say I don't want to hide other possible lifter issues. Moreover the solution I described allows Maat to stop when it needs to _execute_ the unsupported instruction, versus stopping when it lifts the entire basic block containing the instruction.   

I didn't prioritise this issue since you said it was non-blocking but I'll put it on my TODO list for next week :)

**Comment by jordan9001** [comment]
Awesome, thank you.
I obviously don't want to demand free work from you, so I am happy to help if you want. But your described fix would address the main blocker I run into with MAAT. So thank you a bunch for addressing this!
