### ISSUE TITLE
Segmentation fault when running the following

### ISSUE THREAD

**Issue by Jh123x** [trailofbits/maat#126]
Was trying out the tutorial [here](http://maat.re/tutorials/get_started.html) on the `maat.re` page when i encountered a segmentation fault.

Is this the expected behaviour and how to I rectify the problem?

## Code
```python
from maat import *
engine = MaatEngine(ARCH.X86, OS.LINUX)
engine.load("print.bin", BIN.ELF64, args=[b'hello'], load_interp=False)

engine.run()

engine.load("print.bin", BIN.ELF64, args=[b'hello'], load_interp=False)
engine.run()
```

## Output
```bash
[Warning] Couldn't find library 'libc.so.6': skipping import
[Warning] Missing imported function: __cxa_finalize
[Info] Adding object 'print.bin' to virtual fs at '/print.bin'
[Error] MaatEngine::process_store(): Caught memory exception: Writing at address 0x1a8 in page that doesn't have W flag set
[Error] Unexpected error when processing IR instruction, aborting...
[Warning] Couldn't find library 'libc.so.6': skipping import
[Info] Adding object 'print.bin' to virtual fs at '/print.bin'
Segmentation fault (core dumped)

```

**Comment by Boyan-MILANOV** [comment]
Hey @Jh123x 

This is definitely not the expected behaviour :) There are two issues here: 
- the segmentation fault itself was caused by loading the program two times in the same `MaatEngine`, which triggered a bug when adding the same file twice in the symbolic filesystem. Pull request #127 fixes it and Maat will now specify what went wrong instead of crashing: 
    ````
    [Warning] Couldn't find library 'libc.so.6': skipping import
    [Info] Adding object 'print.bin' to virtual fs at '/print.bin'
    Argument starts with: 'h'
    [Warning] Couldn't find library 'libc.so.6': skipping import
    [Info] Adding object 'print.bin' to virtual fs at '/print.bin'
    [Warning] Failed to add the binary in the virtual filesystem due to the following error: FileSystem::create_symlink(): file /proc/1234/exe already exists 
    ````
    Event though Maat won't crash anymore, avoid calling `load()` twice on the same `MaatEngine`.

- you are getting the following error `[Error] MaatEngine::process_store(): Caught memory exception: Writing at address 0x1a8 in page that doesn't have W flag set` because you are using `ARCH.X86` when creating the engine, but then load 64-bit ELF file. So Maat will wrongly execute it as `X86-32` code instead of `X64`. 
  Using `ARCH.X64` instead of `ARCH.X86` makes the program run correctly

**Comment by Jh123x** [comment]
Ohh I see, I will try using `BIN.ELF64` instead.
Thanks for the prompt reply!
