### ISSUE TITLE
Lifter attempts to lift instructions past end of mapped bounds

### ISSUE THREAD

**Issue by jordan9001** [trailofbits/maat#75]
```py
from maat import *

m = MaatEngine(ARCH.X64, OS.LINUX)

m.mem.map(0x410000, 0x411000, PERM.RX)

m.mem.write(0x410000, b"\xeb\xfe", ignore_flags=True)

m.run_from(0x410000, 1)

# tries to lift OOB bytes and fails

print(m.info)
```

The above script results in a failure from Sleigh attempting to decode bytes past the end of the mapped memory.

```
$ python3 example.py
FATAL: Error in sleigh translate(): Sleigh raised a bad data exception: r0x004120b0: Unable to resolve constructor
[Fatal] Lifter error: MaatEngine::run(): failed to lift instructions

Stop:       fatal error in Maat
```
I have also seen other sleigh errors, all referencing memory past what should be mapped.
```
FATAL: Error in sleigh translate(): Can not lift instruction at 0x4110c9: IN AL, 0x3d (unsupported callother occurence)
```

I experience this consistently if I have only mapped a page or less. It will still happen occasionally if I map a greater amount (e.g. `m.mem.map(0x410000, 0x620000)`)
I think it is because the call to `lift_block` specifies a arbitrary code size of `0xfffffff` as seen below.

```c++
lifters[_current_cpu_mode]->lift_block(
                *ir_map,
                addr,
                mem->raw_mem_at(addr),
                0xfffffff,
                0xffffffff,
                nullptr, // is_symbolic
                nullptr, // is_tainted
                true
            )
```

But I am not sure why this issue is not encountered when loading via the lief loader.

**Comment by Boyan-MILANOV** [comment]
Ugh. 😬  Thanks for pointing this out!

We should indeed constrain the code size limit when calling `lift_block` so that it stops at the end of the mapped memory.
The lifter really just lifts instructions from raw bytes and only stops when it encounters a branching instruction. So when lifting uninitialised memory it will just keep lifting out-of-bounds. We should definitely prevent it from reading out of the mapped regions.

Should be pretty easy to fix fortunately :) 

Note: this issue doesn't happen when loading with LIEF because the program executes proper basic blocks ending with branch instructions, so the lifter always stops before trying to lift uninitialised memory and so this bug isn't triggered.
