### ISSUE TITLE
Fatal Error with register translation for eflags reg

### ISSUE THREAD

**Issue by greek-stasia** [trailofbits/maat#80]
Hello there!

I have been playing with pymaat and when I try to execute the instructions `pushf` / `popf` i get the following:
```
FATAL: Error in sleigh translate(): X86: Register translation from SLEIGH to MAAT missing for register eflags
[Fatal] Lifter error: MaatEngine::run(): failed to lift instructions
```

**Comment by Boyan-MILANOV** [comment]
Hi Anastasia,

Thanks for reporting this issue. Sleigh usually uses the bit-wide flag registers (`OF`, `SF`, `CF`, etc) instead of the full `EFLAGS`/`RFLAGS` register. Looking at the sleigh spec file for `x86` it looks like `EFLAGS` is really used only for the `POPF`/`PUSHF` family of instructions. `EFLAGS` as a full register is currently not supported in Maat, because we have defined individual registers for each bit-wide flag. I see 3 possible ways to add support:

- *modify the sleigh file to emulate `EFLAGS` as a concatenation of bit-wide flags*: I don't like this solution, the closer we stay from stock sleigh specifications the better
- *add a support for `EFLAGS` in Maat through a custom getter function*: this requires adding support for register aliasing through custom getter/setter callbacks, which requires some amount of engineering effort, but IMO it is the most elegant solution. Moreover supporting register aliasing might come in handy for other archs we'll add in the future

I'll work on this when I get some time :)

**Comment by Boyan-MILANOV** [comment]
@greek-stasia: I finally found the time to write PR for this: #86

Would you be as kind as to test if it solves your issue? If you don't want to build the branch locally and are able to send me your testing script + binary I can test it myself too. Thanks

**Comment by tiedaoxiaotubie** [comment]
您的邮件我已经收到了，我会尽快处理然后给你回复。谢谢！
